### ISSUE TITLE
ValueError: Requested module name is ambiguous: found 2 appearances of module

### ISSUE THREAD

**Issue by Beliavsky** [lycantropos/run-fortran#1]
Thanks for your project. On Windows I cloned [Minimization](https://github.com/BramvandePut/Minimization) into the directory c:\fortran\public_domain\github\Minimization and tried to run the script, but it says that module ConjugateGradient is defined in two source files, when it is not.

```
c:\python3\code\public_domain\run-fortran>python run-fortran.py run --path "c:\fortran\public_domain\github\Minimization"
Traceback (most recent call last):
  File "run-fortran.py", line 174, in get_module_path_by_module_name
    res, = modules_paths
ValueError: too many values to unpack (expected 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run-fortran.py", line 292, in <module>
    main()
  File "c:\intelpython3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\intelpython3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\intelpython3\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\intelpython3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\intelpython3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "run-fortran.py", line 82, in run
    update_chained_modules_names(modules_names_by_modules_paths)
  File "run-fortran.py", line 202, in update_chained_modules_names
    get_module_path_by_module_name(used_module_name)]
  File "run-fortran.py", line 186, in get_module_path_by_module_name
    raise ValueError(err_msg) from err
ValueError: Requested module name is ambiguous: found 2 appearances of module named "ConjugateGradient" in modules definitions within files located at c:\fortran\public_domain\github\Minimization\ConjugateGradient.f90, c:\fortran\public_domain\github\Minimization\Integrated\Minimization.f90.
```

**Comment by lycantropos** [comment]
...except it is

https://github.com/BramvandePut/Minimization/blob/e48bef3466dcf3e16eafffbdc0dbf8abb7fda44d/ConjugateGradient.f90#L1

https://github.com/BramvandePut/Minimization/blob/e48bef3466dcf3e16eafffbdc0dbf8abb7fda44d/Integrated/Minimization.f90#L519

**Comment by Beliavsky** [comment]
Sorry, you are correct. I was not looking at the file in the Integrated subdirectory. Thanks again for the tool.
